### ISSUE TITLE
Ideias para colocar

### ISSUE THREAD

**Issue by LemosLucas** [LemosLucas/personal-website#5]
## Todo
- [x] Criar página para detalhar melhor as experiências
   - Travei em como iterar sobre os dados .json
   - [x] No início && ao alterar tamanho do browser, calcular a altura da maior experiência. Setar o `min-height: XX` para esta altura para garantir que as setas e a tela não mude de lugar de acordo com o tamanho da experiência atual
   - [x] É possível fazer o swipe entre eles? Adicionar as bolinhas do `iOS` para mostrar a posição atual e os restantes
- [x] Inserir textos e projetos de outras experiências

## Review do Bona
- [x] Dar um final para a história de "comecei a estudar para ciência da computação" para dar um fechamento melhor pra história
- [x] Recomendou citar minha experiência com redes, se possível
- [x] Sugeriu citar os projetos que trabalhei para poder dar mais credibilidade aos skills
	- Faculdade tá dentro
	- Coisas da Siemens seriam super positivas também

## CV
- [x] Create a decent CV version to be shared offline (.pdf)
- [x] Look for ways to generate a CV automatically from the things I'm putting on my site?
	- [x] If not possible, can I provide a way to download my CV automatically from my site?
	  - Pending to understand here how I can fetch the .pdf from the backend and sent so that the frontend can consume it 

---
## Done
- [x] Arrumar breakpoint médio
- [x] Adicionar saudação inicial em alguns idiomas para atualizar automaticamente
- [x] Colocar uma bandeira do Brazil ao falar do fuso horário
- [x] Refatorar component do "SocialIcons" para melhorar reuso
- [x] Remover dependência do `SolidJS`
- [x] É possível fazer o swipe entre eles? Adicionar as bolinhas do `iOS` para mostrar a posição atual e os restante
   - Decidi extrair isto no #6 
- [x] Criar página para posts do Blog
   - Decidi extrair isto no #6
